displayName=NightLegion
author=NightLegion
description=NightLegion companion for BOTW, SOTW, Giveaways and Group Finder
tags=nightlegion,botw,sotw,giveaway,group finder,bossing,skilling,xp
version=
plugins=com.nightlegion.livexp.NightLegionLiveXpPlugin
build=standard
